config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    # get 'home/index'
    resource :home
    resources :secciones do
      resources :paginas
    end
    # resources :users
    # root to: "users#index"
  end

  authenticated :user do
    root 'admin/home#index', as: :authenticated_root
  end

  get 'paginas/:id' => 'visitors#paginas', as: :paginas
  get 'pagina/:pagina' => 'visitors#pagina', as: :pagina

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/pagina.rb
class Pagina < ActiveRecord::Base
  belongs_to :seccion

  extend FriendlyId
  friendly_id :nombre, use: [:slugged, :finders]

  mount_uploader :imagen, ImagenUploader
  serialize :imagen, JSON # If you use SQLite, add this line.

  paginates_per 15

  validates :nombre, presence: true, uniqueness: true
  validates :seccion, presence: true

  scope :activas, ->{ where(active: true) }
end

app/models/seccion.rb
class Seccion < ActiveRecord::Base
  has_many :paginas, dependent: :destroy

  scope :activas, ->{ where(active: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'

  def index; end
end

app/controllers/admin/paginas_controller.rb
class Admin::PaginasController < InheritedResources::Base
  before_action :authenticate_user!
  layout 'admin'

  belongs_to :seccion

  def create
    create! do
      admin_seccion_paginas_path(@seccion)
    end
  end

  def update
    update! do
      admin_seccion_paginas_path(@seccion)
    end
  end

  def pagina_params
    params.require(:pagina).permit(
      :nombre,
      :texto,
      :active,
      :imagen)
  end
end

app/controllers/admin/secciones_controller.rb
class Admin::SeccionesController < InheritedResources::Base
  before_action :authenticate_user!
  layout 'admin'

  def create
    create! do
      admin_secciones_path
    end
  end

  def update
    update! do
      admin_secciones_path
    end
  end

  def seccion_params
    params.require(:seccion).permit(:nombre, :active)
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  add_breadcrumb "home", :root_path

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    # raise 'hola'
    # 1/0
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_secciones, except: [:paginas]

  def pagina
    @pagina = Pagina.find(params[:pagina])
    @seccion = @pagina.seccion
    @mostrar_anuncio = current_user ? false : true
    add_breadcrumb @pagina.nombre, @pagina
  end

  def paginas
    @seccion = Seccion.find(params[:id])
    @paginas = @seccion.paginas.page(params[:page])
  end

  private

  def set_secciones
    @secciones = Seccion.activas
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/paginas_helper.rb
module Admin::PaginasHelper
end

app/helpers/admin/secciones_helper.rb
module Admin::SeccionesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/home/index.html.erb
<h1>Dashboard</h1>

<p>Hola <%= current_user.email %>!!!</p>

app/views/admin/paginas/_form.html.erb
<%= simple_form_for [:admin, @seccion, pagina], html: {class: 'form-horizontal', multipart: true} do |f| %>
  <%= f.input :nombre, label: 'Nombre pagina', hint: 'Este es el nombre de la paginas' %>
  <%= f.input :texto, label: 'Texto', hint: 'Este es el texto de la pagina' %>
  <%= f.input :active, label: 'Activo', hint: 'Activar o desactivar pagina' %>
  <%= f.input :imagen, label: 'Imagen', hint: 'JPEG, PNG, GIF' %>
  <% unless pagina.imagen.blank? %>
  	<%= image_tag(pagina.imagen.url) %>
  <% end %>

  <%= f.button :submit, class: 'btn btn-primary' %>
  <%= link_to 'Cancel', admin_seccion_paginas_path(@seccion), class: 'btn btn-default' %>
<% end %>

app/views/admin/paginas/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h1><%= @seccion.nombre %> - Edit Pagina</h1>
      </div>

      <%= render partial: 'form', locals: {pagina: @pagina} %>
    </div>
  </div>
</div>

app/views/admin/paginas/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h1><%= @seccion.nombre %> - Paginas</h1>
      </div>

      <%= link_to "Nueva Pagina", new_admin_seccion_pagina_path(@seccion), :title => 'Create new Seccion', :class => 'btn btn-default' %>

      <%= content_tag(:table, :class => 'index_table', id: 'paginas') do %>
      <thead>
        <tr>
          <th>&nbsp;</th>
          <th>Nombre</th>
          <th>Activa</th>
        </tr>
      </thead>
      <tbody>
        <% @paginas.each do |pagina| %>
        <%= content_tag_for(:tr, pagina) do %>
        <td><i class="icon-resize-vertical sort-handle"></i></td>
        <td><%= pagina.nombre %></td>
        <td><%= pagina.active %></td>
        <td><%= link_to 'Edit', edit_admin_seccion_pagina_path(@seccion, pagina), title: 'Edit Pagina' %></td>
        <td><%= link_to 'Delete', admin_seccion_pagina_path(@seccion, pagina), method: :delete, data: {confirm: 'Are you sure?'}, title: 'Delete Pagina' %></td>
        <% end %>
        <% end %>
      </tbody>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/paginas/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h1><%= @seccion.nombre %> - Nueva Pagina</h1>
      </div>

      <%= render partial: 'form', locals: {pagina: @pagina} %>
    </div>
  </div>
</div>

app/views/admin/secciones/_form.html.erb
<%= simple_form_for [:admin, @seccion], html: {class: 'form-horizontal', multipart: true} do |f| %>
  <%= f.input :nombre, label: 'Nombre seccion', hint: 'Este es el nombre de la seccion' %>
  <%= f.input :active, label: 'Activo', hint: 'Activar o desactivar seccion' %>

  <%= f.button :submit, class: 'btn btn-primary' %>
  <%= link_to 'Cancel', admin_secciones_path, class: 'btn btn-default' %>
<% end %>

app/views/admin/secciones/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h1>Seccion - Edit Seccion</h1>
      </div>

      <%= render partial: 'form', locals: {seccion: @seccion} %>
    </div>
  </div>
</div>

app/views/admin/secciones/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h1>Seccion - Secciones</h1>
      </div>

      <%= link_to "Nueva Seccion", new_admin_seccion_path, :title => 'Create new Seccion', :class => 'btn btn-default' %>

      <%= content_tag(:table, :class => 'index_table', id: 'seccion') do %>
      <thead>
        <tr>
          <th>&nbsp;</th>
          <th>Nombre</th>
          <th>Activa</th>
          <th>Paginas</th>
        </tr>
      </thead>
      <tbody>
        <% @secciones.each do |seccion| %>
        <%= content_tag_for(:tr, seccion) do %>
        <td><i class="icon-resize-vertical sort-handle"></i></td>
        <td><%= seccion.nombre %></td>
        <td><%= seccion.active %></td>
        <td><%= link_to 'Paginas', admin_seccion_paginas_path(seccion) %></td>
        <td><%= link_to 'Edit', edit_admin_seccion_path(seccion), title: 'Edit Seccion' %></td>
        <td><%= link_to 'Delete', admin_seccion_path(seccion), method: :delete, data: {confirm: 'Are you sure?'}, title: 'Delete Seccion' %></td>
        <% end %>
        <% end %>
      </tbody>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/secciones/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h1>Seccion - New Seccion</h1>
      </div>

      <%= render partial: 'form', locals: {seccion: @seccion} %>
    </div>
  </div>
</div>

app/views/admin/secciones/show.html.erb
<h1>Seccion</h1>

<p>Seccion: <%= @seccion.nombre %></p>
<p>Activa: <%= @seccion.active ? 'Si' : 'No' %></p>
<%= link_to 'Secciones', admin_secciones_path %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="container">
  <hr>
  <footer>
      <div class="row">
          <div class="col-lg-12">
              <p>Copyright &copy; Your Website 2014</p>
          </div>
      </div>
  </footer>
</div>
<!-- /.container -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
        <li>
            <%= link_to 'Services', page_path('services') %>
        </li>
        <li>
            <%= link_to 'Contact', page_path('contact') %>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to '1 Column Portfolio', page_path('portfolio-1-col') %>
                </li>
                <li>
                    <%= link_to '2 Column Portfolio', page_path('portfolio-2-col') %>
                </li>
                <li>
                    <%= link_to '3 Column Portfolio', page_path('portfolio-3-col') %>
                </li>
                <li>
                    <%= link_to '4 Column Portfolio', page_path('portfolio-4-col') %>
                </li>
                <li>
                    <%= link_to 'Single Portfolio Item', page_path('portfolio-item') %>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to 'Blog Home 1', page_path('blog-home-1') %>
                </li>
                <li>
                    <%= link_to 'Blog Home 2', page_path('blog-home-2') %>
                </li>
                <li>
                    <%= link_to 'Blog Post', page_path('blog-post') %>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to 'Full Width Page', page_path('full-width') %>
                </li>
                <li>
                    <%= link_to 'Sidebar Page', page_path('sidebar') %>
                </li>
                <li>
                    <%= link_to 'FAQ', page_path('faq') %>
                </li>
                <li>
                    <%= link_to '404', page_path('404') %>
                </li>
                <li>
                    <%= link_to 'Pricing Table', page_path('pricing') %>
                </li>
            </ul>
        </li>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Application" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= render 'layouts/messages' %>
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked">
          <li><%= link_to 'Secciones', admin_secciones_path %></li>
        </ul>
      </div>
      <div class="col-md-10">  
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Application" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/full-width.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Full Width Page
                <small>Subheading</small>
            </h1>
            <ol class="breadcrumb">
                <li><%= link_to 'Home', root_path %>
                </li>
                <li class="active">Full Width Page</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->

    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12">
            <p>Most of Start Bootstrap's unstyled templates can be directly integrated into the Modern Business template. You can view all of our unstyled templates on our website at <a href="http://startbootstrap.com/template-categories/unstyled">http://startbootstrap.com/template-categories/unstyled</a>.</p>
        </div>
    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/_anuncios.html.erb
<div class="well">
	<h2>anuncios</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa tempore molestiae omnis tempora, quibusdam vero neque ut reiciendis ipsum nemo quae, impedit unde aliquid repellendus voluptate inventore nostrum tenetur voluptatem.</p>
</div>

app/views/visitors/index.html.erb
<!-- Header Carousel -->
<header id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide One');"></div>
      <div class="carousel-caption">
        <h2>Caption 1</h2>
      </div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Two');"></div>
      <div class="carousel-caption">
        <h2>Caption 2</h2>
      </div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Three');"></div>
      <div class="carousel-caption">
        <h2>Caption 3</h2>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>
</header>

<!-- Page Content -->
<div class="container">

  <h3>Home</h3>

  <ul>
    <% Seccion.activas.each do |seccion| %>
    <li>
      <%= link_to seccion.nombre, paginas_path(seccion.id) %>
    </li>
    <% end %>
  </ul>

  <!-- Marketing Icons Section -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">
        Welcome to Modern Business
      </h1>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4><i class="fa fa-fw fa-check"></i> Bootstrap v3.2.0</h4>
        </div>
        <div class="panel-body">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
          <a href="#" class="btn btn-default">Learn More</a>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4><i class="fa fa-fw fa-gift"></i> Free &amp; Open Source</h4>
        </div>
        <div class="panel-body">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
          <a href="#" class="btn btn-default">Learn More</a>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4><i class="fa fa-fw fa-compass"></i> Easy to Use</h4>
        </div>
        <div class="panel-body">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
          <a href="#" class="btn btn-default">Learn More</a>
        </div>
      </div>
    </div>
  </div>
  <!-- /.row -->

  <!-- Portfolio Section -->
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">Portfolio Heading</h2>
    </div>
    <div class="col-md-4 col-sm-6">
      <%= link_to page_path('portfolio-item') do %>
      <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6">
      <%= link_to page_path('portfolio-item') do %>
      <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6">
      <%= link_to page_path('portfolio-item') do %>
      <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6">
      <%= link_to page_path('portfolio-item') do %>
      <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6">
      <%= link_to page_path('portfolio-item') do %>
      <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
      <% end %>
    </div>
    <div class="col-md-4 col-sm-6">
      <%= link_to page_path('portfolio-item') do %>
      <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
      <% end %>
    </div>
  </div>
  <!-- /.row -->

  <!-- Features Section -->
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">Modern Business Features</h2>
    </div>
    <div class="col-md-6">
      <p>The Modern Business template by Start Bootstrap includes:</p>
      <ul>
        <li><strong>Bootstrap v3.2.0</strong>
        </li>
        <li>jQuery v1.11.0</li>
        <li>Font Awesome v4.1.0</li>
        <li>Working PHP contact form with validation</li>
        <li>Unstyled page elements for easy customization</li>
        <li>17 HTML pages</li>
      </ul>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.</p>
    </div>
    <div class="col-md-6">
      <img class="img-responsive" src="http://placehold.it/700x450" alt="">
    </div>
  </div>
  <!-- /.row -->

  <hr>

  <!-- Call to Action Section -->
  <div class="well">
    <div class="row">
      <div class="col-md-8">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
      </div>
      <div class="col-md-4">
        <a class="btn btn-lg btn-default btn-block" href="#">Call to Action</a>
      </div>
    </div>
  </div>

</div>
<!-- /.container -->

<!-- Script to Activate the Carousel -->
<script>
  $(document).on('ready', function () {
    $('.carousel').carousel({
      interval: 1000 //changes the speed
    })
  });
</script>

app/views/visitors/pagina.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <%= render_breadcrumbs %>
      <hr>
      <h1><%= @seccion.nombre %>: <%= @pagina.nombre %></h1>
      <hr>

      <p><%= @pagina.texto %></p>
    </div>
    <div class="col-md-3">
      <%= render :partial => 'anuncios' if @mostrar_anuncio %>
    </div>
  </div>
</div>

app/views/visitors/paginas.html.erb
<h1><%= @seccion.nombre %>: Paginas</h1>
<hr>

<ul>
  <% @paginas.each do |pagina| %>
    <li>
      <%= link_to pagina.nombre, pagina_path(pagina) %>
    </li>
  <% end %>
</ul>

<%= paginate @paginas %>